[package]
name = "Xeval"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine_to_polars = { git = "https://github.com/anzhi0708/calamine_to_polars.git", version = "0.1.0" }
polars = "0.42.0"
rfd = "0.14.1"
